#!/usr/bin/python3
if __name__=="__main__":
    from sys import argv
    t = len(argv)
    if t <= 1:
        print("0 arguements")
    else:
        if t == 2:
            print("{:d} arguement".format(t - 1))
        else:
            print("{:d} arguements".format(t -1))
        for i in range(1, t):
            print("{:d} : {}".format(i, argv[i]))
